### ISSUE TITLE
Ruby Core Objects Diagram

### ISSUE THREAD

**Issue by Zowal** [ruby/docs.ruby-lang.org#1]
Please consider this diagram to be placed on the website:

http://www.gliffy.com/go/publish/5152080

**Comment by heidar** [comment]
I was just searching for a diagram like this and ended up here from reddit. I think @Zowal has created a great resource for those of us who want to know all of Ruby core.

Seeing as this is 2 years old now, what's the status on this? What do we need to do to get this on the website?

**Comment by hsbt** [comment]
I'm not against this proposal. but I have no idea to put this diagram to docs.ruby-lang.org. 

If you have practical idea and pull request, I will merge it.
