### ISSUE TITLE
Change of documentation paths in 2022

### ISSUE THREAD

**Issue by zverok** [ruby/docs.ruby-lang.org#130]
I can't identify the exact change that caused this, but 
* for many years, and as recent as of Jan 26, 2022, all files in `doc/` folder of the Ruby repository [produced](https://web.archive.org/web/*/https://docs.ruby-lang.org/en/3.1/doc/syntax/methods_rdoc.html) paths looking like **doc**/syntax/methods_rdoc.html
* as of now, they [became](https://docs.ruby-lang.org/en/3.1/syntax/methods_rdoc.html) just 3.1/syntax/methods_rdoc.html (no `doc/` prefix)

I am afraid that might've broken a lot of links on the Internet. I noticed because all the links to generic language docs in my [Ruby Changelog](https://rubyreferences.github.io/rubychanges/3.1.html) became 404.

I wonder can this change be reverted, or, alternatively, can redirects be introduced between the old and new scheme?..

**Comment by znz** [comment]
I added redirects.
https://github.com/ruby/docs.ruby-lang.org/commit/1b02ac798911be8f2b0bc8209d65046e41b2f501
