### ISSUE TITLE
How do we contribute docs changes?

### ISSUE THREAD

**Issue by mattwelke** [ruby/docs.ruby-lang.org#132]
Hi. I was running some code samples from the docs today and noticed that the output I got didn't match what the docs showed (version 3.1.2). I was going to do a quick PR to correct them but I can't find the docs contents anywhere in this repo. The README for the repo doesn't mention how to contribute to docs, and skimming over the page https://www.ruby-lang.org/en/documentation/ I also can't find any instructions there for how to contribute.

Thanks!

**Comment by hsbt** [comment]
Please submit your changes to https://github.com/ruby/ruby. We generated https://docs.ruby-lang.org/ from the canonical ruby repository.

You can generate doc root with `make html` on ruby repo.
