### ISSUE TITLE
Accessibility issues

### ISSUE THREAD

**Issue by dmarcoux** [ruby/docs.ruby-lang.org#134]
Hey,

I find docs.ruby-lang.org quite hard on the eyes whenever I need to read documentation. I had a look at WAVE (Web Accessibility Evaluation Tool) and here's the report for the `Hash` page:

https://wave.webaim.org/report#/https://docs.ruby-lang.org/en/3.1/Hash.html

![light-mode](https://user-images.githubusercontent.com/1102934/206442263-83a14d1f-7aeb-4b27-8115-f4471670de75.png)

**Comment by wilcornish** [comment]
+1 on this, the comments in code examples are completely unreadable for me (protanopic colour blind)

**Comment by hsbt** [comment]
We welcome your improvement via pull-request.
