### ISSUE TITLE
Codeblock red is too dark

### ISSUE THREAD

**Issue by akirataguchi115** [ruby/docs.ruby-lang.org#137]
Let's take an example: https://docs.ruby-lang.org/en/master/Method.html#method-i-to_s
Is it just me or is the red "output" not so easy to read when one dims down the brightness of the screen?

**Comment by st0012** [comment]
I've addressed this in the latest theme 🙂 

<img width="80%" alt="Screenshot 2024-10-24 at 22 37 26" src="https://github.com/user-attachments/assets/11ee13f9-871c-48f5-9e61-efaf9ab1b59f">

**Comment by akirataguchi115** [comment]
Thanks!
