### ISSUE TITLE
Clickable for no reason

### ISSUE THREAD

**Issue by akirataguchi115** [ruby/docs.ruby-lang.org#138]
For example here: https://docs.ruby-lang.org/en/master/Method.html#method-i-to_s 

The text is clickable without any apparent reason like so: https://stackoverflow.com/questions/4442217/css-make-a-div-clickable

**Comment by st0012** [comment]
I think this issue has been fixed with the latest theme 🙂

**Comment by akirataguchi115** [comment]
Seems like so. Thanks for the heads up!
