### ISSUE TITLE
navigation broken

### ISSUE THREAD

**Issue by schmurfy** [ruby/docs.ruby-lang.org#15]
It has been a while (since the naming convention was changed I think), just follow these steps:

go to http://www.ruby-doc.com/ and then:

- click on "Core" link at the top => 404
- click on "2.2.0 core" => 404
(this only fails for the latest release, the others work fine)

The issue is that it tries to redirect to "/core-2.0" where the correct path is "/core-2.2.0"

**Comment by hsbt** [comment]
www.ruby-doc.com is NOT our sites.
