### ISSUE TITLE
Japanese document page has "http" URL image

### ISSUE THREAD

**Issue by uu59** [ruby/docs.ruby-lang.org#24]
> index.html:110 Mixed Content: The page at 'https://docs.ruby-lang.org/ja/latest/doc/index.html' was loaded over HTTPS, but requested an insecure image 'http://i.creativecommons.org/l/by/3.0/88x31.png'. This content should also be served over HTTPS.

It is redirected to HTTPS URL https://licensebuttons.net/l/by/3.0/88x31.png, directly use HTTPS version is better.

**Comment by hsbt** [comment]
Thank you for reporting.

I've been addressed this issue to upstream. see https://github.com/rurema/doctree/issues/313

note: I will keep this issue open until upstream fixes.

**Comment by hsbt** [comment]
Fixed.
