### ISSUE TITLE
新VMのタイムゾーンがUTC

### ISSUE THREAD

**Issue by sho-h** [ruby/docs.ruby-lang.org#34]
新VMのタイムゾーンがUTCになっててcronが指定した時間から9時間ずれて実行されてるようでした。

```
$ date
Tue Aug 29 13:24:22 UTC 2017 # 22:24に実行
```

**Comment by okkez** [comment]
時差を計算して、前と同じ時間に実行されるようにしておきました。

# Timezone を Asia/Tokyo にするのとどっちがいいんだろうか。

**Comment by sho-h** [comment]
おぉ、ありがとうございます！Timezoneを修正するかは悩ましいですね...

**Comment by hsbt** [comment]
ja だけではなくて en もある関係上、どこかは昼になっていて更新をいつ実行しても同じかなあと思います。なので UTC のままでいいかなあ。

**Comment by sho-h** [comment]
おぉ、たしかに。じゃあこれでcloseしちゃいますね。
