### ISSUE TITLE
Let's Encrypt の cron を入れた

### ISSUE THREAD

**Issue by hsbt** [ruby/docs.ruby-lang.org#35]
VM 移設時に忘れていました。

```
@monthly certbot renew --quiet && systemctl reload nginx
```

というのを root の crontab に入れたので共有します。 /cc @okkez @sho-h

**Comment by okkez** [comment]
連絡、ありがとうございます！

**Comment by sho-h** [comment]
どもですー。

**Comment by znz** [comment]
renewal された時だけ reload するなら `--renew-hook "systemctl reload nginx"` とかどうでしょうか。

それから、`@monthly` だと http://blog.n-z.jp/blog/2017-04-26-certbot-renew.html に書いたように数回失敗するだけで期限切れになってしまうので、 `@daily` で (できれば `perl -e 'sleep int(rand(3600))' &&` などのランダムスリープをいれて) 実行する方が良いのではないでしょうか。
