### ISSUE TITLE
メンテナンス中はメンテナンスページを表示してほしい

### ISSUE THREAD

**Issue by sho-h** [ruby/docs.ruby-lang.org#5]
以下のようなものを見かけたりしましたので、メンテナンスの際は簡単なメンテナンス中ページでも表示してもらえるとありがたいのですが、可能でしょうか？

* https://twitter.com/myokoym/status/447703609698811904
* https://twitter.com/xmisao/status/447658749516210176

**Comment by okkez** [comment]
解決しているようなので閉じます。
