### ISSUE TITLE
Some links broken in README

### ISSUE THREAD

**Issue by willnet** [ruby/docs.ruby-lang.org#56]
Links of `COPYING`, and `CONTRIBUTING.md` seem to be broken in https://docs.ruby-lang.org/en/trunk/ . They return 404.

I'm not sure that this Issue related to here. sorry if it's wrong.

**Comment by znz** [comment]
`win32/README.win32` too.

**Comment by znz** [comment]
ref: [Some links broken in README](https://bugs.ruby-lang.org/issues/14743)

**Comment by hsbt** [comment]
Fixed by https://bugs.ruby-lang.org/projects/ruby-master/repository/git/revisions/2898805535104c330e1e5c64c8065a108f1f2895/diff/README.md
