### ISSUE TITLE
jaの更新が止まっている

### ISSUE THREAD

**Issue by sho-h** [ruby/docs.ruby-lang.org#61]
public以下をls -lすると `Sep 26 02:50` の更新が最後のようです。

**Comment by sho-h** [comment]
> 誰も心当たりなければ夜に直接コマンド叩いてみようかしらという感じです。

enは実は更新されてて、jaだけが問題でした。9/26なのはcap deployした日のままだからでした。(symlinkも作り直すのかと思ってたらそういえばそんな必要なかった...

直接コマンドを叩いてみた結果、特に追加のログは出なかったですが、どこでもraiseしなかったので処理自体は最後まで進んでるのとnilの出力はあまり重要ではない(purge-fastly-key系の出力だった)事がわかったのでレポジトリを覗いてみたら更新できてませんでしたのでcloneしなおしました。

```
$ git pull --depth 1 --rebase origin master
remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
From https://github.com/rurema/doctree
 * branch              master     -> FETCH_HEAD
First, rewinding head to replay your work on top of it...

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: empty ident name (for <(null)>) not allowed
$ git branch
* (HEAD detached from refs/heads/master)
  master
$ git checkout master
Previous HEAD position was f50bc896... Merge pull request #1485 from scivola/fix-link-to-Fixnum#%-from-symref
Switched to branch 'master'
Your branch and 'origin/master' have diverged,
and have 1 and 1 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)

$ git branch
* master

$ git log
commit 0528a215ee583696893233a5c4593b4a6c4c93d1
Author: Sho Hashimoto <...>
Date:   Sat Sep 15 07:10:08 2018 +0900

    Merge pull request #1435 from long-long-float/fix-file-join

    File#joinの説明を修正
...
```

よくわかってないですが、作り直したら以下のようになり更新できました。(差分がないと再現しないかどうかの区別は付いてないです

```
$ git pull --depth 1 --rebase
remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
Current branch master is up to date
```

最近gitパッケージに更新があったのがなにか関係してるのかしら...

ともかく、2、3日様子を見て引き続きgit pullできればcloseしようと思います。

**Comment by hsbt** [comment]
対応ありがとうございます! cron-apt などパッケージのアップデートは適当なタイミングで実行してるのでその辺が何か踏んだのかもしれません。

**Comment by znz** [comment]
> Your branch and 'origin/master' have diverged,

ということはリモートにないコミットがローカルに入ってるように見えます。

心当たりがないなら
https://qiita.com/hnw/items/5ac4416c72dd567b263f
によると `git reset --hard origin/master` すれば良さそう?

**Comment by sho-h** [comment]
depth 1でgit logも1件しか出ないからその辺はないと思っちゃってたんですけど、そういえばresetは試してなかったですね。前のを残してるので今晩試してみますねー。

**Comment by sho-h** [comment]
`git reset --hard origin/master` したら確かに直りました。あと今日分の修正が反映されている事を確認しました。

**Comment by sho-h** [comment]
引き続き問題なさそうですのでcloseします。
