### ISSUE TITLE
生成をやめたバージョンの静的ファイルのバックアップ

### ISSUE THREAD

**Issue by sho-h** [ruby/docs.ruby-lang.org#78]

**Comment by sho-h** [comment]
~sho-h/backup以下にen/jaの2.0.0〜2.3.0までバックアップしました。圧縮したら数MBほどなので、コミットしようかとも思いましたけど、現状はそこまではしていません。

**Comment by znz** [comment]
https://ftp.ruby-lang.org/pub/ruby/doc/ に残しておくのが (たぶんミラーもされて) 良さそうに思います。
