### ISSUE TITLE
最近のbitclustの更新が反映されていなさそう

### ISSUE THREAD

**Issue by hanachin** [ruby/docs.ruby-lang.org#84]
マージされたPRの変更がぱっとみ反映されてなさそうに見えます。

たとえばこちらではmetaタグでviewportを追加したのですが
https://github.com/rurema/bitclust/pull/76

HTMLにはviewportが含まれておらず

```
$ curl -s https://docs.ruby-lang.org/ja/latest/doc/index.html | grep viewport
```

こちらではタイトルの末尾にリファレンスマニュアルと明記しましたが

https://github.com/rurema/bitclust/pull/78

付け加えられていないように見えます

```
$ curl -s https://docs.ruby-lang.org/ja/latest/doc/index.html | grep title
  <title>オブジェクト指向スクリプト言語 Ruby リファレンスマニュアル (Ruby 2.6.0)</title>
```

**Comment by hsbt** [comment]
2019/11/29 8:00 くらいにデプロイしてみました。まだ `cap deploy` による手動デプロイなので、マージしただけではデプロイされないというのが現状です。

ひとまず @znz さんもデプロイできるようにしておくので、当面は @hsbt か @znz に声かける感じでお願いします。

**Comment by hanachin** [comment]
なるほど！手動デプロイが必要なんですね。デプロイありがとうございます :pray:

**Comment by hanachin** [comment]
@znz さんが修正 & 更新してくれたみたいで、更新の反映が確認できたので閉じます :pray: 
https://github.com/rurema/doctree/pull/2041
